-- Oracle schema for gallery app

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE favorites CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE inquiries CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE car_images CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE cars CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE users_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE cars_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE car_images_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE inquiries_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE users (
  user_id NUMBER PRIMARY KEY,
  full_name VARCHAR2(120) NOT NULL,
  email VARCHAR2(180) NOT NULL UNIQUE,
  password_hash VARCHAR2(255) NOT NULL,
  role VARCHAR2(20) DEFAULT 'USER' NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  last_login_at TIMESTAMP NULL,
  is_active NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN')),
  CONSTRAINT chk_users_active CHECK (is_active IN (0, 1))
);

CREATE TABLE cars (
  car_id NUMBER PRIMARY KEY,
  brand VARCHAR2(80) NOT NULL,
  model VARCHAR2(80) NOT NULL,
  year NUMBER(4) NOT NULL,
  price NUMBER(12,2) NOT NULL,
  mileage NUMBER(10) NOT NULL,
  fuel_type VARCHAR2(40),
  gear_type VARCHAR2(40),
  color VARCHAR2(40),
  description CLOB,
  status VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
  created_by NUMBER NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  sold_at TIMESTAMP NULL,
  is_deleted NUMBER(1) DEFAULT 0 NOT NULL,
  CONSTRAINT fk_cars_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
  CONSTRAINT chk_cars_status CHECK (status IN ('AVAILABLE', 'SOLD')),
  CONSTRAINT chk_cars_deleted CHECK (is_deleted IN (0, 1))
);

CREATE TABLE car_images (
  image_id NUMBER PRIMARY KEY,
  car_id NUMBER NOT NULL,
  image_path VARCHAR2(400) NOT NULL,
  sort_order NUMBER DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_car_images_car FOREIGN KEY (car_id) REFERENCES cars(car_id) ON DELETE CASCADE
);

CREATE TABLE favorites (
  user_id NUMBER NOT NULL,
  car_id NUMBER NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_favorites PRIMARY KEY (user_id, car_id),
  CONSTRAINT fk_favorites_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_favorites_car FOREIGN KEY (car_id) REFERENCES cars(car_id) ON DELETE CASCADE
);

CREATE TABLE inquiries (
  inquiry_id NUMBER PRIMARY KEY,
  user_id NUMBER NOT NULL,
  car_id NUMBER NOT NULL,
  message CLOB NOT NULL,
  status VARCHAR2(20) DEFAULT 'NEW' NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  handled_by NUMBER NULL,
  handled_at TIMESTAMP NULL,
  CONSTRAINT fk_inq_user FOREIGN KEY (user_id) REFERENCES users(user_id),
  CONSTRAINT fk_inq_car FOREIGN KEY (car_id) REFERENCES cars(car_id),
  CONSTRAINT fk_inq_admin FOREIGN KEY (handled_by) REFERENCES users(user_id),
  CONSTRAINT chk_inq_status CHECK (status IN ('NEW', 'IN_PROGRESS', 'CLOSED'))
);

CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE cars_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE car_images_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE inquiries_seq START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE INDEX idx_cars_status ON cars(status);
CREATE INDEX idx_cars_brand_model ON cars(brand, model);
CREATE INDEX idx_cars_price ON cars(price);
CREATE INDEX idx_cars_year ON cars(year);
CREATE INDEX idx_inquiries_status ON inquiries(status);

COMMIT;
